Update objective-c-xcode.yml

diff --git a/.github/workflows/objective-c-xcode.yml b/.github/workflows/objective-c-xcode.yml
--- a/.github/workflows/objective-c-xcode.yml
+++ b/.github/workflows/objective-c-xcode.yml
@@ -34,6 +34,19 @@ jobs:
       - name: Clean derived data
         run: rm -rf ~/Library/Developer/Xcode/DerivedData
 
+   #   - name: Build project
+     #   run: |
+   #       xcodebuild -workspace __MACOSX/SignIn/SignIn.xcodeproj/._project.xcworkspace -scheme SignIn clean archive -configuration release -sdk iphoneos -archivePath SignIn.xcarchive
+
+
       - name: Build project
         run: |
-         xcodebuild -workspace __MACOSX/SignIn/SignIn.xcodeproj/._project.xcworkspace -scheme SignIn clean archive -configuration release -sdk iphoneos -archivePath SignIn.xcarchive
+          xcodebuild -workspace __MACOSX/SignIn/SignIn.xcodeproj/._project.xcworkspace -scheme SignIn clean archive -configuration release -sdk iphoneos -archivePath SignIn.xcarchive
+        continue-on-error: true
+
+      - name: Check for xcodebuild errors
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "xcodebuild failed with exit code ${{ job.status }}."
+            exit 1
+          fi
